version: 2.1
orbs:
  terraform: "circleci/terraform@3.1.0"
  moneysmart-orb: moneysmartco/circleci-orb@0.0.39
  aws-cli: circleci/aws-cli@3.1
default-image: &default-image
  machine:
    image: "ubuntu-2004:2022.04.1"
    docker_layer_caching: true
jobs:
#-----------------
# PullRequest
#-----------------
  tf_lint:
    <<: *default-image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - terraform/install:
          terraform_version: 0.13.5
      - run:
          name: Install tflint
          command: |
            curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.21.0/tflint_linux_amd64.zip && sudo unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: tf fmt
          command: |
            terraform fmt -check=true -diff=true
            tflint
  tf_validate:
    <<: *default-image
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - terraform/install:
          terraform_version: 0.13.5
      - run:
          name: tf validate, init & plan
          command: |
            terraform validate
workflows:
  pr-steps:
    jobs:
      - tf_lint:
          context: terraform
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
      - tf_validate:
          context: terraform
          requires:
            - tf_lint
          filters:
            tags:
              ignore: /^v.*/
            branches:
              ignore: master
